GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "user";

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "user";

GRANT CONNECT ON DATABASE olist_db TO "user";

GRANT REFERENCES ON ALL TABLES IN SCHEMA public TO "user";

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "user";

CREATE EXTENSION IF NOT EXISTS pgcrypto;
GRANT EXECUTE ON FUNCTION gen_random_uuid() TO "user";
